### ISSUE TITLE
Some weird "set color mode" issue

### ISSUE THREAD

**Issue by Sir-Quack-III** [jwlodek/py_cui#106]
I know this question has been asked before, but the fix for it didn't apply to my code. The code is very simple, and I don't know what's happening.

What's supposed to happen is then when the button is pressed, it runs the `hello()` function, which adds a label to the screen saying `You Pressed me!`. But, an error pops up saying `AttributeError: 'NoneType' object has no attribute 'set_color_mode'`.

Here is my code:
```python
import py_cui

root = py_cui.PyCUI(14, 18)

def hello():
    root.add_label("You Pressed me!", 0, 0)

button = root.add_button('Button Text', 1, 2, column_span=2, command=hello())
root.start()
```

**Comment by jwlodek** [comment]
When you pass in `command` to the `add_button` function, you should only pass the function name, and not call it:

```Python
button = root.add_button('Button Text', 1, 2, column_span=2, command=hello)
```

Aside from that, this actually seems to be a bug - if you add a widget after the `start` method is called, a renderer is seemingly not assigned to the newly created widget. I'll try and fix it tomorrow. As a band-aid fix, you can try the following (although this is not a great long-term solution I think)

```Python
import py_cui

root = py_cui.PyCUI(14, 18)

def hello():
    label = root.add_label("You Pressed me!", 0, 0)

    # Manually assign the global renderer here
    label._assign_renderer(root._renderer)

button = root.add_button('Button Text', 1, 2, column_span=2, command=hello)
root.start()
```

**Comment by jwlodek** [comment]
This bug should now be fixed on the master branch, and the fix will be included in the next release version
