### ISSUE TITLE
Conform to PEP8 guidelines

### ISSUE THREAD

**Issue by PabloLec** [jwlodek/py_cui#112]
In most of python files, PEP8 guidelines are not applied, and these lines are reported by linters.  

This includes: 
- Multiple spaces around operators
``` python
self._command           = command
```
- Multiline docstring that could be one-liner.
``` python
"""Need to update all cursor positions on resize
"""
```
- Spaces around keyword argument assignments
``` python
def add_block_label(self, title, row, column, row_span = 1, column_span = 1, padx = 1, pady = 0, center=True):
```
- Unnecessary white spaces.
``` python
self._renderer.draw_text(  self, self._title, target_y - 2, centered=True, selected=True)
```

There is also some inconsistency with the use of single and double quotes. Even though single quotes seem to be mostly used.  

I could format existing code to follow PEP8 guidelines. But this would mean changing nearly all the python files. Which could be a problem for other current work.

**Comment by PabloLec** [comment]
Any chance we could make it a `v0.1.5` milestone ?

Basically just run `black` on this bad boy.
Also, I saw unused imports, star imports that could be replaced, etc.
I'd like to make a quick cleaning in a segmentated PR in order to continue on a good basis for v0.1.5. And maybe it's a good timing since I think there is nothing big being currently implemented.

How does it sounds?

**Comment by jwlodek** [comment]
I'm OK with this, with the exception that I would actually prefer docstrings to be two lines even if they are just one line. Reason being is I'm following the numpy docstring guidelines, which actually has it this way: https://numpydoc.readthedocs.io/en/latest/format.html#short-summary

Also, subjectively, I prefer the way that looks. Everything else I'm OK with auto-cleaning up
