### ISSUE TITLE
Can't unset the exit key

### ISSUE THREAD

**Issue by lenormf** [jwlodek/py_cui#115]
**Describe the bug**
I don't want the program to quit upon hitting any one single key. I can't set `exit_key` to `None` or `0`.

**To Reproduce**
1. Pass `exit_key=None` to the `PyCUI` constructor
2. Start the UI

Errors:

```
Traceback (most recent call last):
  File "/home/fle/misc/4dE/./4dE.py", line 65, in <module>
    sys.exit(main(sys.argv))
  File "/home/fle/misc/4dE/./4dE.py", line 51, in main
    root = UserInterface(2, 2)
  File "/home/fle/misc/4dE/./4dE.py", line 12, in __init__
    super().__init__(rows, columns, exit_key=None)
  File "/home/fle/misc/4dE/.env/lib/python3.9/site-packages/py_cui/__init__.py", line 141, in __init__
    exit_key_char = py_cui.keys.get_char_from_ascii(exit_key)
  File "/home/fle/misc/4dE/.env/lib/python3.9/site-packages/py_cui/keys.py", line 44, in get_char_from_ascii
    return chr(key_num)
TypeError: an integer is required (got type NoneType)
```

Upon passing `exit_key=0`, the program doesn't start (no output even in debug mode).

**Expected behavior**
The program doesn't close upon hitting any keys.

**Comment by lenormf** [comment]
My workaround for now is to pass `exit_code=1` to the `PyCUI` constructor.

**Comment by PabloLec** [comment]
This could be implemented easily.

By returning None if key is None in `PyCUI.get_char_from_ascii()`.
The only other thing to consider would be: 
``` python
self._init_status_bar_text  = f'Press - {exit_key_char} - to exit. Arrow Keys to move ' \
                                       'between widgets. Enter to enter focus ' \
                                       'mode.'
```
A simple if-statement would be acceptable I think.

**Comment by jwlodek** [comment]
Also would need to make sure to somehow handle the use of the exit key in the main draw loop if that is None
