### ISSUE TITLE
Multiple selection of items in a scroll menu

### ISSUE THREAD

**Issue by lenormf** [jwlodek/py_cui#117]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to select several items in a scroll menu.

**Describe the solution you'd like**
Looking at the code, it seems that the index of the single item selected is stored in a `_selected_item` attribute. I'd like that to be a list of item indexes.

**Comment by jwlodek** [comment]
Did you try using the checkbox menu? That allows for multiple item selection

**Comment by lenormf** [comment]
I didn't notice that widget. I overloaded it, and it seems to be working well, thanks!
