### ISSUE TITLE
Allow setting a default value for text box popups

### ISSUE THREAD

**Issue by lenormf** [jwlodek/py_cui#118]
**Is your feature request related to a problem? Please describe.**
Text box popups cannot be instantiated with a default text value.

**Describe the solution you'd like**
Have `TextBoxPopup` take a default text value, forwarded to the `Popup` and `TextBoxImplementation` parent instances.

**Comment by pkazmier** [comment]
Yes, this would be nice. At the moment, I have to access the private `_popup` variable so I can set the default text value. In my case, it's a search query and I want to populate the popup with the last query, so they can edit instead of start all over.

```python
root.show_text_box_popup("Filter expression:", popup_callback)
root._popup.set_text(last_filter_expression)
```

**Comment by jwlodek** [comment]
I have added this on the `v0.1.5` branch by adding an `initial_text` kwarg to the `show_text_box_popup` function
