### ISSUE TITLE
Cycling widgets from overview mode skips the first one

### ISSUE THREAD

**Issue by lenormf** [jwlodek/py_cui#121]
**Describe the bug**
The first widget added to a UI will be skipped upon cycling.

**To Reproduce**
1. Start the UI, with a couple widgets added one after the other
2. Cycle widgets with the set key
3. The second widget is focused

**Expected behavior**
The first widget gets focused first, as it was never selected.

**Comment by jwlodek** [comment]
Can reproduce on my system. I guess from overview mode it should always cycle to the first widget.
