### ISSUE TITLE
Check whether a menu is empty elegantly

### ISSUE THREAD

**Issue by lenormf** [jwlodek/py_cui#142]
**Is your feature request related to a problem? Please describe.**
I currently have to rely on `get()` returning `None` to check whether a menu is empty, which is inelegant. I can't check the index of the currently selected item either because of #139.

**Describe the solution you'd like**
An implementation of `empty()` on menu classes.

**Comment by jwlodek** [comment]
This is now fixed on the v0.1.5 branch with a new `is_empty` function for menus.
