### ISSUE TITLE
Cannot restart a PyCUI instance

### ISSUE THREAD

**Issue by PabloLec** [jwlodek/py_cui#147]
**Describe the bug**
PyCUI instances cannot be restarted after using `.stop()` due to the `_stopped` flag remaining set to True.
This a problem especially if you try to handle multiple views and go back to a previous one.

**To Reproduce**

1. Create two PyCUI instances
2. Start the first one.
3. Start the second instance and `.stop()` the first one.
4. Try to stop the second instance and re-`.start()` the first one.

**Comment by jwlodek** [comment]
Closing as your fix seems to resolve this issue.
