### ISSUE TITLE
Cannot update widgets in a for or while loop

### ISSUE THREAD

**Issue by StevenTeglman** [jwlodek/py_cui#158]
See the following:

```python
import time
import py_cui

class Counter:
    def __init__(self, master: py_cui.PyCUI):

        self.master = master

        self.todo_scroll_cell = self.master.add_text_box('Increases Numbers', 0, 0, row_span=1, column_span=1)
        self.todo_scroll_cell.add_key_command(py_cui.keys.KEY_ENTER, self.increase_number)
    
    def increase_number(self):
        for i in range(0,6):
            print(i)
            self.todo_scroll_cell.set_text(str(i))
            time.sleep(0.5)
            


# Create the CUI with 7 rows 6 columns, pass it to the wrapper object, and start it
root = py_cui.PyCUI(7, 6)
s = Counter(root)
root.start()
```

I'm expecting the text box to update with each number from 0 to 5, yet it only updates once the for loop is exited. 

I'm not sure if this is expected behavior, or not. If this is expected, how would I update the text box each iteration of the loop?

**Comment by PabloLec** [comment]
Hi! 

Yes, the synchronous `time.sleep` blocks the UI refresh. You need to make it asynchronous and set a suitable refresh timeout, a working example could be:

``` python
import time
import py_cui

from threading import Thread

class Counter:
    def __init__(self, master: py_cui.PyCUI):

        self.master = master

        self.todo_scroll_cell = self.master.add_text_box('Increases Numbers', 0, 0, row_span=1, column_span=1)
        self.todo_scroll_cell.add_key_command(py_cui.keys.KEY_ENTER, self.run_increase_number)

    def _increase_number(self):
        for i in range(6):
            self.todo_scroll_cell.set_text(str(i))
            time.sleep(0.5)

    def run_increase_number(self):
        t = Thread(target=self._increase_number)
        t.start()

root = py_cui.PyCUI(7, 6)
root.set_refresh_timeout(0.5)
s = Counter(root)
root.start()
```

If you need some kind of long and blocking work use threading or multiprocessing.
I also did have to deal with this stuff, you can check my code on [RecoverPy](https://github.com/PabloLec/RecoverPy) (especially `search` module) to get an idea on how to work on it.

**Comment by StevenTeglman** [comment]
Wonderful! @PabloLec  Thanks so much for your solution, that solved my problem. Also @jwlodek thank you for your reply, and for this wonderful library! Might not be a bad idea to include something on this topic in the Docs, though.
