### ISSUE TITLE
CUI not accessable, after posting terminal output to window

### ISSUE THREAD

**Issue by voryzen** [jwlodek/py_cui#166]
**Describe the bug**
On py_cui v0.1.4
set a screen with 1 x 1 grid (with no widgets) to show the output of a terminal command (needed to be interactive)
when the terminal output is done, and a new widget set is applied, the new widget set does not work, other than 'focusing'

e.g: scroll menu will focus, but when manipulating it (scrolling, choosing a item) it will lose focus. This behaviour happens with all widgets

**To Reproduce**
1. Create a screen with a button that runs an interactive terminal command/script in another screen
2. create a screen 1 x 1, with no widgets, (otherwise output from command 'pushes' the CUI 'upwards')
3. set a new screen to run/appear (get_widget_set) when command is finished
4. run/click button, interact with command and let py_cui try to load the specified widget set 

Hopefully I explained that well enough

**Expected behavior**
Widgets should act normally, instead of losing focus

**Screenshots**

**Environment*:*
 - OS: Manjaro
 - Terminal: konsole
 - Version: Py_CUI: 0.1.4

**Comment by PabloLec** [comment]
So if I'm understanding correctly you are using `print()`?

**Comment by voryzen** [comment]
Yea, its technically an ansible playbook, so all output would be via print()

**Comment by PabloLec** [comment]
I'm not sure if there is a bug, that would be great if you could provide your code.

Basically using `print()`, using standard output, probably messes with the curses main loop in some way.
You could possibly use a widget to display your first command output like a text box or a scroll menu.

But from what I understand, you could use your first screen with a button to trigger your function.
On trigger, just stop `py_cui` and run your function normally, hence using stdout **without any `py_cui`/curses instance running**.
On completion, start a new `py_cui` instance.

This way, by exiting/restarting `py_cui`, I think everything should be fine.

**Comment by voryzen** [comment]
I had a similar idea, but due to other functions, I don't think I can stop the CUI; stopping the CUI would reset the global variables and such.

As far as functioning goes, I can start the CUI, and use tmux to create another session to run the command, but when the tmux session finishes, the CUI is not usable. I'm perplexed as to why this is.

Focusing works, and the widget set is in the right places, no issues there. It's just that all other functions are not available. eg. I can't scroll through scroll menus, it just loses focus; button cease to work, they just unfocus too.

The project is based heavily on pyautogit, thats the 'framework' I started coding python with. I'll look into the possibility of how curses might interact with tmux. if you have any other ideas, @PabloLec let me know

**Comment by PabloLec** [comment]
Using `root.stop()` and `root.start()` will preserve your instance and thus instance vars, etc. That should only "pause it", exit the main loop, and restart looping when you call `start()`. I think it will do the job for your use case.

**Comment by voryzen** [comment]
@PabloLec ahh I see. that is interesting. I'll let you know what I come up with

**Comment by voryzen** [comment]
That was a touch of genius, @PabloLec 

I guess this isn't really a bug.. maybe it should be a feature?
