### ISSUE TITLE
[FIX] For list index out of range when clicking blank space with mouse in a MenuPopup

### ISSUE THREAD

**Issue by Fr0st3h** [jwlodek/py_cui#176]
Change (In popups.py)
`if viewport_top <= y and viewport_top + len(self._view_items) - self._top_view >= y:`

To

`if viewport_top <= y and viewport_top + (len(self._view_items) - 1) - self._top_view >= y:`

**Comment by jwlodek** [comment]
Thanks! Fix included in `v0.1.6`
