### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by lukehabets** [jwlodek/py_cui#25]
Just as a suggestion for people confused why they are unable to install with pip, if getting error 'py-cui requires Python '>=3.2' but the running Python is 2.7.17', you must use pip3 to install once cloned.

**Comment by jwlodek** [comment]
Yeah it should be `pip3` if both python 3 and python 2 are installed side by side

**Comment by lukehabets** [comment]
Yes, just wanted to put that out there incase anyone was having an issue. Maybe note in the .readme about it if you feel it's a good idea.

**Comment by jwlodek** [comment]
@lukehabets yeah I just made a commit and added it to the README

**Comment by lukehabets** [comment]
Ok cool
