### ISSUE TITLE
osx delete key doesnt work

### ISSUE THREAD

**Issue by drewwebster** [jwlodek/py_cui#27]
on macbook pro delete key doesnt work on all examples.

in autogit.py it appends ?^? to text entered in input box

i suspect its the ascii key code with curses. 
i tried code 8 - that is ascii key code for delete key on mac (?)

found this curses code, but not with solution

https://www.programcreek.com/python/example/21642/curses.KEY_DC

**Comment by drewwebster** [comment]
okay i found  a fix. now i can type in textbox and use delete key

 in keys.py i changed to:

# Pressing backspace returns 8 on windows?
if platform == 'win32':
    KEY_BACKSPACE   = 8
elif platform == 'darwin':
    KEY_BACKSPACE = 127
else:
    KEY_BACKSPACE   = curses.KEY_BACKSPACE

**Comment by jwlodek** [comment]
Could you make a pull request with that fix? I don't have access to a MacOS machine, so I wasn't able to test on that platform.

**Comment by drewwebster** [comment]
ok will do

**Comment by jwlodek** [comment]
Closing, resolved with v0.1.0
