### ISSUE TITLE
Set color mode issue.

### ISSUE THREAD

**Issue by cptbldbrd** [jwlodek/py_cui#28]
I got a strange error while working with py-cui. When I execute my code everything looks great but when I press enter on one of my buttons it gives me this error. Any ideas?

`File "/usr/local/lib/python3.7/dist-packages/py_cui/widgets.py", line 381, in draw
    self.renderer.set_color_mode(self.color)
AttributeError: 'NoneType' object has no attribute 'set_color_mode'
`

**Comment by cptbldbrd** [comment]
Never mind that was my bad...

**Comment by jwlodek** [comment]
Would you mind letting me know what was causing the problem? In case anyone else runs into the same issue

**Comment by cptbldbrd** [comment]
I had a label initialized in one class and tried to change what the label said after pressing a button. I have changed the code and never committed the faulty code. Sorry I don't have a good example of it right now. I will try to recreate the error later tonight and post the code the caused the issue. Thanks for reaching out!

**Comment by jwlodek** [comment]
Great thanks. From the error I'm guessing that at some point one of the widgets was made `NoneType` which caused the `draw` call to fail.
