### ISSUE TITLE
Logger Implementation

### ISSUE THREAD

**Issue by telday** [jwlodek/py_cui#38]
It would make the debugging process significantly easier if there was some type of logging ability. I would propose an INFO level logger, which would output to a file and then could be used to diagnose user issues, as well as a DEBUG level logger which could either output to the status bar or somewhere else on the screen while the TUI is still being drawn. The best resource for this would be pythons builtin [logging](https://docs.python.org/3.8/library/logging.html) module

This will be next on my list if someone else doesn't implement it first.

**Comment by jwlodek** [comment]
I am working on this, bit busy at the moment, but once I have some more time I'll finish it up.

**Comment by jwlodek** [comment]
Closing, resolved with v0.1.0
