### ISSUE TITLE
KEY_TAB to switch between widgets and provide focus

### ISSUE THREAD

**Issue by pkazmier** [jwlodek/py_cui#46]
For the app I built, I found the Overview and Focus modes a bit unfriendly to use. I have three widgets on my screen as follows. 
```
+--------------------------------------------------------------------------+
|                                     |                                    |
|                                     |                                    |
|                                     |                                    |
|-------------------------------------|                                    |
|                                     |                                    |
|                                     |                                    |
|                                     |                                    |
+--------------------------------------------------------------------------+
```

Arrow navigation felt a bit wonky in overview mode (as previously reported by a different user), so I wanted to simply make consecutive `TAB` presses cycle through the three widgets and placing it in focus mode automatically.

So, here is what I did in case anyone else wants to do the same:
```
        focus = itertools.cycle(root.widgets.values())

        def select_next_widget():
            root.move_focus(next(focus))

        root.add_key_command(py_cui.keys.KEY_TAB, select_next_widget)
        menu1.add_key_command(py_cui.keys.KEY_TAB, select_next_widget)
        menu2.add_key_command(py_cui.keys.KEY_TAB, select_next_widget)
        menu3.add_key_command(py_cui.keys.KEY_TAB, select_next_widget)
```

**Comment by jwlodek** [comment]
So the problem with this is that for the textbox/textblock widgets, when in focus mode the tab key is used to write a tab. I could make it so that it moves between widgets in overview mode pretty easily, but I'm not sure how to handle those cases when in focus mode.

**Comment by jwlodek** [comment]
I've thought about this, and I think the way we can do it is to allow the user to specify a key to cycle through the different widgets. Then in the case that no text entry widgets are used, and the Tab key would be best, they can just run the function with the tab key.

**Comment by pkazmier** [comment]
Sounds reasonable. Maybe we could offer some means of disabling the TAB key in text widgets as well, so users can opt out if they don’t expect users to use the key.

My use case does not have any inputs. Here is a link to my project that uses your library in one of its user-definable commands as well as a screenshot of it.

https://github.com/fmr-llc/awsrun/blob/master/README.md#last-command

 It is using version 0.3 for now as it works after my changes for tabbing, page up/down, etc .. I know you’ve been adding these features and once it stabilizes I’ll go back and update it.

Thanks for making this port. I needed something fast a month ago and I am glad to have found your project.
