### ISSUE TITLE
BlockLabel: wrong center text

### ISSUE THREAD

**Issue by wdog** [jwlodek/py_cui#51]
I think I've found a little bug.

The parameter `center=True|False` is not working because in the method `add_block_label` in `__init__.py` when creating  the widget `LabelBlock` I've found the last 2 parameter inverted (logger and center)

_**fix**_

```python
new_label   = widgets.BlockLabel(id,  ..., center,  self._logger)
 ```

**Comment by jwlodek** [comment]
Oh wow, thanks for this. Will include fix with `v0.1.1`.
