### ISSUE TITLE
set_title does nothing for BlockLabels

### ISSUE THREAD

**Issue by WardBrian** [jwlodek/py_cui#63]
Because BlockLabels uses `_lines` instead of  `_title`, set_title does nothing.

To reproduce:

    import py_cui
    root = py_cui.PyCUI(2,2)
    root.set_title('Block Labels')
    label = root.add_block_label('Hello\nWorld', 0,0, row_span=2, column_span=2)
    label.set_title('Goodbye\nWorld')
    root.start()

**Expected behavior**
set_title(title) should set the BlockLabel's ._lines attribute to title.splitlines(), or an alternative function should be supplied to set the lines attribute directly.

**Environment*:*
 - OS: Windows 10
 - Terminal: Powershell Core
 - Version: 0.1.1

**Comment by jwlodek** [comment]
I think this is a duplicate of https://github.com/jwlodek/py_cui/issues/60, it should be fixed in version 0.1.2, which I want to release as soon as I have some time to do some expanded testing.
