### ISSUE TITLE
Support for more mouse functions

### ISSUE THREAD

**Issue by jwlodek** [jwlodek/py_cui#72]
**Is your feature request related to a problem? Please describe.**
Currently only standard mouse presses are supported, other mouse operations should be handled more gracefully.

**Describe the solution you'd like**
Handle double clicks, right mouse clicks, and maybe mouse holds and drags.

**Additional context**
Additionally, it would be nice to allow a right mouse press to open a context menu in the terminal at the pressed location, as a popup subclass.

**Comment by jwlodek** [comment]
While playing around with this, found that mouse support is broken for windows terminal, made an issue here: https://github.com/microsoft/terminal/issues/8682

**Comment by jupiterbjy** [comment]
Seems like your issue was marked as duplicate and closed.
On that referenced issue I [found](https://github.com/microsoft/terminal/issues/376#issuecomment-733198098) that they could use VT sequence instead of win32, breaking windows-curses module.

Maybe it's better to issue on _windows-curses_ to support VT sequence instead?

**Comment by jwlodek** [comment]
I suppose it would be worthwhile, though the `windows-curses` repo on github is mostly a mirror of the project and only wraps the C library with a python wrapper. I'm not exactly sure where the original C library is located, and how to submit a feature request to it. I'll make an issue with the python implementation project, though I'm not sure they will be able to implement the changes on their end - though maybe they will know how to reach the maintainer

**Comment by jwlodek** [comment]
Additional mouse press functions have been implemented and added to the v0.1.4 branch, awaiting release. Closing this issue
