### ISSUE TITLE
Wrong help text for ScrollMenu

### ISSUE THREAD

**Issue by jupiterbjy** [jwlodek/py_cui#75]
https://github.com/jwlodek/py_cui/blob/8ebdaa642dc381e0f3111fd2af1867b22420941f/py_cui/widgets.py#L407

As far as I can tell - There was no built-in command parameters or functions with *KEY_ENTER* in ScrollMenu class, but help text is saying as if.

Might be better to remove those to prevent confusions just like I had.

**Comment by jwlodek** [comment]
Ah good catch, I almost always assign `KEY_ENTER` to some command, so it never occurred to me that this is incorrect by default.

**Comment by jwlodek** [comment]
Fixed with 96c1c1832373821c77d51a98212721fd9a339a59

**Comment by jupiterbjy** [comment]
I made a mistake, and it's too minor to make a PR.

Since all other widgets' class name does not include word 'widget' in it, I did same for the slider, forgetting that it's script name. I'm terribly sorry.

https://github.com/jwlodek/py_cui/blob/092d6e345d954422376d795a8be3c86c466139c1/py_cui/__init__.py#L765-L767

Should change to ```.slider.SliderWidget```.
```python
    def add_slider(self, title, row, column, row_span=1,
                   column_span=1, padx=1, pady=0,
                   min_val=0, max_val=100, step=1, init_val=0) -> py_cui.control_widgets.slider.SliderWidget:
``` 

Just found this out when trying out sliders minutes ago.

By the way, is slider incomplete? I'm not seeing borders for this one.

![image](https://user-images.githubusercontent.com/26041217/105734205-bc4e6a00-5f75-11eb-971c-221930b85c80.png)

**Comment by jwlodek** [comment]
I did not develop the slider widget, it was done by another contributor, but I don't think it ever had a border included. You could always make a PR adding a toggle border option for the slider if you want. I'll fix the annotation error on my end

**Comment by jupiterbjy** [comment]
Ah, that also explains why there's stray emtpy class in ```slider``` module, I see. Since even example for slider is broken, I'll make a PR on this.
