### ISSUE TITLE
I can't enter text in a language other than English 

### ISSUE THREAD

**Issue by Vamporelol** [jwlodek/py_cui#78]
What should I look for to add the ability to enter text in Russian?

![image](https://user-images.githubusercontent.com/65223631/104119884-42a76100-5365-11eb-87c2-fc0dc523a9eb.png)

**Comment by jwlodek** [comment]
Support for other character sets would be nice... I'll have to look into that at some point. At the moment the only thing I could think of is having a dictionary mapping of `py_cui` key codes (maybe the alt-modified ones) to cyrillic symbols, then override the handle key press function for the textbox class, where if it detects a key in the alt modified range, it prints the corresponding character from the dictionary.

**Comment by jwlodek** [comment]
Closing as per your PR. I'm going to open another issue that will track improved expanded language support integration.
